### ISSUE TITLE
Overwrites Statamic's Link fieldtype

### ISSUE THREAD

**Issue by mikemartin** [jonassiewertsen/Link-fieldtype#1]
Hey @jonassiewertsen 

It looks your addon replaces the Statamic's existing Link fieldtype. The Link fieldtype is used for entry links and creating page redirects in v3. 

It might be best to rename your fieldtype to something like "URL" so it doesn't conflict.

**Comment by jonassiewertsen** [comment]
Hey @mikemartin 

You're right about that. Thanks for letting me know. 

That conflict hasn't been there in the beginning, so the naming felt good back then.

**Comment by jonassiewertsen** [comment]
Has been closed via v1.1.0
