### ISSUE TITLE
Update support for Statamic 3.1

### ISSUE THREAD

**Issue by bdroberson** [jonassiewertsen/Link-fieldtype#10]
Ability to use on Statamic 3.1 - thanks!

**Comment by jonassiewertsen** [comment]
I will get to it as soon as I can. 

Feel free to create a PR if you are faster than myself :-)

**Comment by bdroberson** [comment]
Not sure what's needed? Possibly this:
"statamic/cms": "3.0.* || 3.1.*",

Would like to use on v3.1. Thanks.
