### ISSUE TITLE
Laravel 9 compatibility?

### ISSUE THREAD

**Issue by justinhough** [jonassiewertsen/Link-fieldtype#26]
When trying to install with Laravel 9. I get the following error.

I do have one package that requires `"illuminate/support": "^9.0",`, but I think the easiest fix is if 

["illuminate/support": "^8.0", ](https://github.com/jonassiewertsen/statamic-external-link/blob/master/composer.json#L11)
just had a support for `^8.0|^9.0`.

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires jonassiewertsen/statamic-external-link ^1.5 -> satisfiable by jonassiewertsen/statamic-external-link[v1.5.0].
    - jonassiewertsen/statamic-external-link v1.5.0 requires illuminate/support ^8.0 -> found illuminate/support[v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require jonassiewertsen/statamic-external-link:*" to figure out if any version is installable, or "composer require jonassiewertsen/statamic-external-link:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

Let me know if you'd like me to put in a PR for this.

Have been using a lot of your packages I realized and they each fill a big need. Thank!

**Comment by jonassiewertsen** [comment]
Thanks for creating that issue!

The simple truth is, I need to check all packages and need to update them 🙄

I have been pretty busy, but should be able to do so the next couple of days.
Feel free to remind me in a few days, if I havent updated soon 😊
