### ISSUE TITLE
Statamic 3.4 support

### ISSUE THREAD

**Issue by sunscreem** [jonassiewertsen/Link-fieldtype#37]
Hey @jonassiewertsen 

Can I request this is updated to work with 3.4?

**Comment by jonassiewertsen** [comment]
Let me know if it does work as expected: https://github.com/jonassiewertsen/statamic-external-link/releases/tag/v1.7.0

**Comment by sunscreem** [comment]
@jonassiewertsen Thank you - seems to be working perfectly. (I noticed the changelog in statamic was blank though)
